config/routes.rb
Rails.application.routes.draw do
  resources :items do
    resources :offers do
      resources :comments
    end
  end

  get 'auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get '/auth/:provider/callback', :to => 'sessions#callback'
  root to: 'home#index'
  get 'home/index'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  extend Enumerize

  enumerize :status, in: %i(negotiating close), default: :negotiating

  belongs_to :item
  belongs_to :user

  has_many :comments

  def comment(body, writer)
    comment = comments.build(body: body, user_id: writer.id)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    item = Item.find(params[:item_id])

    @offer = item.offers.build
    @offer.user = current_user

    respond_to do |format|
      if @offer.save
        format.html { redirect_to item, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        raise
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.slim
= simple_form_for(@offer) do |f|
  = f.error_notification

  .form-inputs
    = f.input :status
    = f.input :item_id
    = f.input :user_id

  .form-actions
    = f.button :submit

app/views/offers/edit.html.slim
h1 Editing offer

== render 'form'

= link_to 'Show', @offer
'|
= link_to 'Back', offers_path

app/views/offers/index.html.slim
h1 Listing offers

table
  thead
    tr
      th Status
      th Item
      th User
      th
      th
      th

  tbody
    - @offers.each do |offer|
      tr
        td = offer.status
        td = offer.item_id
        td = offer.user_id
        td = link_to 'Show', offer
        td = link_to 'Edit', edit_offer_path(offer)
        td = link_to 'Destroy', offer, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Offer', new_offer_path

app/views/offers/new.html.slim
h1 New offer

== render 'form'

= link_to 'Back', offers_path

app/views/offers/show.html.slim
p#notice = notice

p
  strong Status:
  = @offer.status
p
  strong Item:
  = @offer.item_id
p
  strong User:
  = @offer.user_id

= link_to 'Edit', edit_offer_path(@offer)
'|
= link_to 'Back', offers_path