config/routes.rb
Rails.application.routes.draw do
  resources :items do
    resources :offers do
      resources :comments
    end
  end

  get 'auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get '/auth/:provider/callback', :to => 'sessions#callback'
  root to: 'home#index'
  get 'home/index'

end

app/models/item.rb
class Item < ActiveRecord::Base

  scope :all_taken, ->{where(classification: :taken)}
  scope :all_given, ->{where(classification: :given)}

  extend Enumerize

  # sample code
  # enumerize :sex, in: {male: 1, female: 2}

  enumerize :classification, in: %i(given taken)
  enumerize :status, in: %i(open negtiating close), default: :open

  mount_uploader :image1, ItemImageUploader
  mount_uploader :image2, ItemImageUploader
  mount_uploader :image3, ItemImageUploader

  has_many :offers

  def offered?(user)
    !!offer(user)
  end

  def offer(user)
    return nil unless user

    id = user.kind_of?(Numeric) ? user : user.id

    offers.find_by(user_id: id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @offer = @item.offer(current_user)
    @comment = @offer.comments.build if @offer
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :category, :image1, :image2, :image3, :prefecture, :city, :classification, :status, :user_id, :remove_image1, :remove_image2, :remove_image3)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.slim
= simple_form_for(@item) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :category
    = f.input :image1, as: :image_preview, input_html: { preview_version: :thumb }
    = f.input :image2, as: :image_preview, input_html: { preview_version: :thumb }
    = f.input :image3, as: :image_preview, input_html: { preview_version: :thumb }
    = f.input :prefecture, as: :select, collection: ["北海道", "大阪", "沖縄"].map.with_index(1){|v, i| [v, i]}
    = f.input :city
    = f.input :classification, item_wrapper_class: "radio-inline", as: :radio_buttons

  .form-actions
    = f.button :submit

app/views/items/edit.html.slim
h1 Editing item

== render 'form'

= link_to 'Show', @item
'|
= link_to 'Back', items_path

app/views/items/index.html.slim
h1 Listing items

table
  thead
    tr
      th Name
      th Description
      th Category
      th Image1
      th Image2
      th Image3
      th Prefecture
      th City
      th Classification
      th Status
      th User
      th
      th
      th

  tbody
    - @items.each do |item|
      tr
        td = item.name
        td = item.description
        td = item.category
        td = item.image1
        td = item.image2
        td = item.image3
        td = item.prefecture
        td = item.city
        td = item.classification
        td = item.status
        td = item.user_id
        td = link_to 'Show', item
        td = link_to 'Edit', edit_item_path(item)
        td = link_to 'Destroy', item, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Item', new_item_path

app/views/items/new.html.slim
h1 New item

== render 'form'

= link_to 'Back', items_path

app/views/items/show.html.slim
javascript:
  $(function () {
    $("img.change_photo").click(function () {
      var ImgSrc = $(this).attr("src");
      var ImgAlt = $(this).attr("alt");
      var main_photo = $("#main_photo");
      main_photo.attr({src: ImgSrc, alt: ImgAlt});
      main_photo.hide();
      main_photo.fadeIn("slow");
      return false;
    });
  });
p#notice = notice
.row
  .col-md-6
    .panel.panel-default
      .panel-body
        .wrapper.text-center
          p = image_tag @item.image1.url, id: 'main_photo'
          ul.list-inline
            li = image_tag @item.image1.url, class: 'change_photo', width: '100x100'
            li = image_tag @item.image2.url, class: 'change_photo', width: '100x100'
            li = image_tag @item.image3.url, class: 'change_photo', width: '100x100'
  .col-md-6
    .panel.panel-default
      .panel-heading
        h1.panel-title
          span.label.label-warning = @item.classification.text
          = @item.name
      .panel-body
        p
          = nl2br @item.description
        h4
          strong Category:
        p
          =  @item.category
        h4
          strong Prefecture:
        p
          = Prefecture.find(@item.prefecture).name
          = @item.city

.row
  .col-md-6
  .col-md-6
    - # noinspection RubyQuotedStringsInspection
    = link_to '交渉開始', item_offers_path(@item), class: 'btn btn-primary btn-block pull-right', method: :post unless @item.offered?(current_user)

- if @item.offered?(current_user)
  = simple_form_for([@item, @offer, @comment]) do |f|
    = f.error_notification

    .form-inputs
      = f.input :body

    .form-actions
      = f.button :submit

  .comments
    - @offer.comments.each do |comment|
      p = comment.body


= link_to 'Edit', edit_item_path(@item)
'|
= link_to 'Back', items_path